################################
#昔式重复任务 Xi's Repeat Task V1.2.5
#这是昔式插件的第二个力...
#至于第一个...源码丢了....
#支持下吧 QWQ 我爱你
#昔式插件第一个为Xi'sAutoTask
#################################


#################################
#tasks不能动
#task1 task2为任务名，可以自定义，仅限数字字母
#delay为两次执行指令的间隔 单位为秒
#command 为执行的指令
#插件有BUG一定在mcbbs上提出来，我会尽力修改。插件毕竟简单，有可能的话后续会开源
#################################
tasks:
  task1:
    delay: 5
    command: say Hello, World!
  task2:
    delay: 10
    command: say How are you?